Update readme.md test
joinbuzz/buzzer_download pull request #6
Opened 2022-12-12 16:03 UTC by bselwe

2022-12-13 08:48 UTC, bselwe commented
@rafaelortizzableh test comment

2022-12-13 10:52 UTC, bselwe commented
test

2022-12-13 10:53 UTC, bselwe commented on readme.md
> +To download Buzz, go into [Releases](https://github.com/joinbuzz/buzzer_download/releases), click on [`Download Buzzer - Latest`](https://github.com/joinbuzz/buzzer_download/releases/tag/download-lat
Test

2022-12-13 11:00 UTC, bselwe commented
test

2022-12-13 11:00 UTC, bselwe commented
test

2022-12-13 11:01 UTC, bselwe commented
test 2

2022-12-13 11:02 UTC, bselwe commented on readme.md
> +To download Buzz, go into [Releases](https://github.com/joinbuzz/buzzer_download/releases), click on [`Download Buzzer - Latest`](https://github.com/joinbuzz/buzzer_download/releases/tag/download-lat
test

2022-12-13 11:06 UTC, bselwe commented
Test

2022-12-13 11:07 UTC, bselwe commented
@rafaelortizzableh test mention

2022-12-13 11:08 UTC, bselwe commented
Test

2022-12-13 11:09 UTC, bselwe commented on readme.md
> -To download Buzz, go into [Releases](https://github.com/joinbuzz/buzzer_download/releases), click on [`Download Buzzer - Latest`](https://github.com/joinbuzz/buzzer_download/releases/tag/download-lat
Test

2022-12-13 11:17 UTC, bselwe commented
Test

2022-12-13 11:17 UTC, bselwe commented
Test

2022-12-21 12:23 UTC, ebbacc commented on readme.md
> -To download Buzz, go into [Releases](https://github.com/joinbuzz/buzzer_download/releases), click on [`Download Buzzer - Latest`](https://github.com/joinbuzz/buzzer_download/releases/tag/download-lat
123 test

2022-12-21 12:25 UTC, ebbacc requested changes

2022-12-21 12:25 UTC, ebbacc commented on readme.md
> -To download Buzz, go into [Releases](https://github.com/joinbuzz/buzzer_download/releases), click on [`Download Buzzer - Latest`](https://github.com/joinbuzz/buzzer_download/releases/tag/download-lat
123

2023-01-09 12:09 UTC, closed without merging